spring:
  datasource:
    url: jdbc:${database.type}://${database.postgres.host}:${database.postgres.port}/${database.postgres.name}
    username: ${database.postgres.username}
    password: ${database.postgres.password}

  jpa:
    hibernate:
      ddl-auto: validate

database:
  type: postgresql
  postgres:
    host: localhost
    port: 5432
    name: enroll
    username: postgres
    password: password

jwt:
  signingKey: secret
  accessTokenDuration: 1
  refreshTokenDuration: 3600

server:
  port: 8099
